# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 01:46
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('clashwar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cards', jsonfield.fields.JSONField()),
            ],
        ),
    ]
