# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 03:09
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('clashwar', '0003_decks'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeckCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popularCards', jsonfield.fields.JSONField()),
                ('decks', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.AlterField(
            model_name='decks',
            name='place',
            field=models.CharField(max_length=100),
        ),
    ]
