# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-04 05:58
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('clashwar', '0004_auto_20170726_0309'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularDecks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winrate', models.CharField(max_length=30)),
                ('imgs', jsonfield.fields.JSONField()),
            ],
        ),
    ]
