# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-07 07:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clashwar', '0005_populardecks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arenacards',
            name='percentage',
        ),
        migrations.RemoveField(
            model_name='arenacards',
            name='title',
        ),
    ]
